name: terraform-workflow

on:
  push:
    branches: [ master ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Init Test Code 
        uses: docker://hashicorp/terraform:0.12.29
        with:
          entrypoint: terraform
          args: init ./tests/s3/
          
      - name: Lint Test Code
        uses: docker://wata727/tflint:0.19.1
        with:
          args: --loglevel debug --module ./tests/s3/
      
      - name: Validate Test Code 
        uses: docker://hashicorp/terraform:0.12.29
        with:
          entrypoint: terraform
          args: validate ./tests/s3/ -no-color

  dynamic-analysis:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: s3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Init Test Code
        uses: docker://hashicorp/terraform:0.12.29
        with:
          entrypoint: terraform
          args: init ./tests/s3/

      - name: Apply Test Code
        uses: docker://hashicorp/terraform:0.12.29
        with:
          entrypoint: terraform
          args: apply -auto-approve ./tests/s3/
      
      - name: Destroy Test Code
        uses: docker://hashicorp/terraform:0.12.29
        with:
          entrypoint: terraform
          args: destroy -auto-approve ./tests/s3/
