name: terraform-workflow

on:
  push:
    branches: [ master ]

jobs:
  # Static Analysis of the Terraform module and its code
  # Stuff like linters, etc.
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      # Initialize the Terraform code
      - name: Init Test Code 
        uses: docker://hashicorp/terraform:0.12.29
        with:
          entrypoint: terraform
          args: init ./tests/s3/
       
      # Lint the Terraform code 
      # Using: https://github.com/terraform-linters/tflint
      - name: Lint Test Code
        uses: docker://wata727/tflint:0.19.1
        with:
          args: --loglevel debug --module ./tests/s3/
      
      # Validate the Terraform code using inbuilt
      # validate command
      - name: Validate Test Code 
        uses: docker://hashicorp/terraform:0.12.29
        with:
          entrypoint: terraform
          args: validate ./tests/s3/ -no-color

  # Dynamic analysis of the Terraform module and its code
  # Stuff like unit tests, E2E tests, etc.
  dynamic-analysis:
    runs-on: ubuntu-latest
    
    # The LocalStack mocks the AWS services, enabling
    # local development without any costs
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: s3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Init Test Code
        uses: docker://hashicorp/terraform:0.12.29
        with:
          entrypoint: terraform
          args: init ./tests/s3/

      # Apply Terraform code
      - name: Apply Test Code
        uses: docker://hashicorp/terraform:0.12.29
        with:
          entrypoint: terraform
          args: apply -auto-approve ./tests/s3/
      
      #############################
      # Verify here the resources #
      # were created successfully #
      #############################

      # (Probably optional) Clean up the created resources
      - name: Destroy Test Code
        uses: docker://hashicorp/terraform:0.12.29
        with:
          entrypoint: terraform
          args: destroy -auto-approve ./tests/s3/
