name: terraform-workflow

on:
  push:
    branches: [ master ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Lint Code
        uses: docker://wata727/tflint
        with:
          volumes: "$GITHUB_WORKSPACE:/data"
          entrypoint: /bin/sh
          args: |
            -c "\
             apk update && \
             apk add terraform && \
             cd $GITHUB_WORKSPACE/terraform/test && \
             terraform init && \
             tflint --loglevel debug --module"
